### ISSUE TITLE
Use compare() to compare strings

### ISSUE THREAD

**Issue by Murmele** [LinuxDevon/dbc_parser_cpp#16]
![grafik](https://user-images.githubusercontent.com/10099533/218438998-bdf13618-cbb6-4457-b37e-974c28fef5e1.png)

**Comment by LinuxDevon** [comment]
Should be fixed in the latest merge commit: 829cff4aeb5cb2d772eed866d37b0007188237db. Turned on warning and automated builds and caught this. Please reopen if this is not fixed.
