### ISSUE TITLE
libdbc::Message::m_size has no get accessor?

### ISSUE THREAD

**Issue by nickpelling** [LinuxDevon/dbc_parser_cpp#19]
libdbc::Message::m_id has a get accessor ("id()") in message.hpp, but m_size doesn't, is there a specific reason for that?

Happy to raise a pull request if not. :-)

**Comment by LinuxDevon** [comment]
This should be resolved in the latest merge: 829cff4aeb5cb2d772eed866d37b0007188237db. It was an oversight that it wasn't there. Thank you for the catch!
