### ISSUE TITLE
what() methods are private

### ISSUE THREAD

**Issue by Murmele** [LinuxDevon/dbc_parser_cpp#2]
Why the what methods are private?
```cpp

	class exception : public std::exception {
		const char * what() const throw() {
			return "libdbc exception occurred";
		}
	};

	class validity_error : public exception {
		const char * what() const throw() {
			return "Invalid DBC file...";
		}
	};
```

**Comment by LinuxDevon** [comment]
Good catch on that! I looked at the tests and just validated that they were thrown. I didn't check if you could access `what` method. That needs to be fixed and is definitely not meant to be that way.

**Comment by Murmele** [comment]
Thanks :) I am using currently your library in labplot. Thanks for the library!

**Comment by LinuxDevon** [comment]
You are very welcome! Haven't heard of this program before. Looks really neat!
