### ISSUE TITLE
Feature: Better error messages

### ISSUE THREAD

**Issue by Murmele** [LinuxDevon/dbc_parser_cpp#22]
Currently only a validity_error() is thrown if the dbc file is not correct. Maybe introducing an enum which will be returned with the error to indicate where the error is located and a function to convert the enum to a string error message.

https://github.com/LinuxDevon/dbc_parser_cpp/blob/753119d6615674876d5f21216438d8dd663bca92/src/dbc.cpp#L204-L250

**Comment by LinuxDevon** [comment]
That is doable i think. So there is a mix of exceptions and return status right now. So if i were to do it at that level I would probably make other classes. 

I guess maybe a refactoring is in order here. I might just change all of the results to returns. Do you have thoughts or issues with that?

**Comment by Murmele** [comment]
Is it possible to return such an enum also from the exception? So you don't have to refactor everything to `return`s?

**Comment by LinuxDevon** [comment]
Yea that is possible. I can add that enum to there and give a function to expose. The other option would be to create other classes for each instance.

```cpp
enum ValidtyErrorReason {
  NON_DBC_FILE,
  MISSING_NAMESPACE_SECTION,
...

class ValidityError : public Exception {
public:
        ValidtyErrorReason reason() {
              return ...
};
```

or could do derivatives of the class?

```c++
class NonDbcFileError : public ValidityError {
public:
	const char* what() const throw() override {
		return "Not a dbc file.";
	}
};
```

Let me know what you think.
