### ISSUE TITLE
CMake minimum required version issue 

### ISSUE THREAD

**Issue by gerlachs** [LinuxDevon/dbc_parser_cpp#23]
Building with CMake version 3.16 up to 3.22 fails. CMakeLists.txt uses FILE_SET which requires CMake 3.23 but minimum required CMake version is set to 3.16.

**Comment by LinuxDevon** [comment]
Thank you for the catch! sorry for the oversight. Just pushed a fix to main. Not ready for release since i have a few other changes to make. It will be in the next release though.

**Comment by gerlachs** [comment]
Requiring cmake 3.23 is a big limitation. Many distributions does not support this yet, like the current OpenSUSE 15.5 which has cmake 3.20. Would it be possible to keep 3.16 as minimum required version and replace FILE_SET with a cmake 3.16 equivalent?

**Comment by LinuxDevon** [comment]
Yea that can work. I'll make that change when i get a moment and can setup a test for that.

**Comment by LinuxDevon** [comment]
This is closed and included in `v0.3.0`
