### ISSUE TITLE
Decoding messages

### ISSUE THREAD

**Issue by Murmele** [LinuxDevon/dbc_parser_cpp#3]
Are you planing to implement decoding messages?

**Comment by LinuxDevon** [comment]
Honestly, I haven't been working on / using this library since I wrote it. It was more of a project to learn cmake on and a simple library to parse basic dbcs. I will take a look though and see about implementing those decoded message.

**Comment by Murmele** [comment]
I checked out CAN tools of python. Maybe I will implement it in the meantime and create a MR

**Comment by LinuxDevon** [comment]
Sounds good. Yea that is the reference I was using as well. Let me know if you need any help.

**Comment by LinuxDevon** [comment]
Closed by #12
