### ISSUE TITLE
std::stod considers locale

### ISSUE THREAD

**Issue by Murmele** [LinuxDevon/dbc_parser_cpp#8]
I have a german system and therefore "," is used as decimal separator. In this case std::stod expects "," as decimal separator, but the dbc file uses always ".".

Therefore a different approach for converting doubles has to be used

https://stackoverflow.com/questions/12316972/how-to-tweak-stdstod-string-to-double-for-decimal-separator-and-number-of-di

**Comment by LinuxDevon** [comment]
@Murmele Is this closed by #12 as well?

**Comment by Murmele** [comment]
yes this can be closed

**Comment by LinuxDevon** [comment]
Was just looking over this again. Can you give me an example of the locale you are using? Debating weather this was a double conversion issue or not. I see the regex strings only match on `.` that is probably the issue. Writing up a test right now to test this but want to see what you have an input.

**Comment by Murmele** [comment]
Hi,
no the problem is that in the dbc file always . is used. But if I would like to convert for example "3.14" to a double and my locale is set to , the conversion failed on my computer
